### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PeerRich** [PeerRich/no.str.bio#1]
- [ ] move usernames and npubs into single usernames.json 
- [ ] generate nostr.json on build with usernames
- [ ] move redirect to client pages/[redirect].tsx
- [ ] add `<Meta>` to [redirect].tsx to add custom og-image (vercel/og)
- [ ] check if the username is taken
- [ ] include username of choice in LN invoice
- [ ] automate assignment of username
- [ ] eventually move usernames.json into a database
- [ ] dynamically create nostr.json if usernames change
